// =============================================
// slownik.js — Polish dictionary for Alfabet
// Hospital communication aid
// =============================================

// --- Quick Phrases (hospital scenarios) ---
const PHRASES = {
  'Potrzeby': ['Chcę pić', 'Chcę jeść', 'Zimno mi', 'Gorąco mi', 'Chcę spać'],
  'Ból': ['Boli mnie głowa', 'Boli mnie brzuch', 'Boli mnie ręka', 'Coś mnie boli'],
  'Pomoc': ['Zawołaj pielęgniarkę', 'Proszę podnieść łóżko', 'Proszę położyć łóżko', 'Potrzebuję pomocy'],
  'Rozmowa': ['Jak tam u ciebie?', 'Co słychać?', 'Dziękuję', 'Kocham cię', 'Tak', 'Nie'],
  'Samopoczucie': ['Czuję się dobrze', 'Czuję się źle', 'Lepiej mi', 'Gorzej mi']
};

// --- Sentence starters ---
const STARTERS = [
  'Ja', 'Czy', 'Jak', 'Chcę', 'Proszę', 'Nie', 'Gdzie', 'Kiedy',
  'Co', 'To', 'Mam', 'Jestem', 'Mogę', 'Kto', 'Dlaczego', 'Ile',
  'Tak', 'Bardzo', 'Dziękuję'
];

// --- Dictionary (~1000 common Polish words, sorted alphabetically with Polish locale) ---
const DICTIONARY = [
  'a',
  'adres',
  'akurat',
  'albo',
  'ale',
  'alergia',
  'ani',
  'antybiotyk',
  'aparat',
  'apteka',
  'autobus',
  'babcia',
  'bać',
  'badanie',
  'bandaż',
  'bardziej',
  'bardzo',
  'bark',
  'bez',
  'bezpieczny',
  'będę',
  'będzie',
  'będziesz',
  'biały',
  'biec',
  'bielizna',
  'biodro',
  'bliski',
  'blisko',
  'bluzka',
  'bo',
  'bogaty',
  'bok',
  'bolec',
  'bolesny',
  'boli',
  'brać',
  'brat',
  'brew',
  'brudny',
  'brzuch',
  'brzydki',
  'budynek',
  'budzić',
  'butelka',
  'buty',
  'być',
  'był',
  'była',
  'było',
  'całkiem',
  'całkowicie',
  'cały',
  'cel',
  'cena',
  'chce',
  'chcesz',
  'chcę',
  'chcieć',
  'chętnie',
  'chleb',
  'chłodny',
  'chodzi',
  'chodzić',
  'chory',
  'chroniczny',
  'chwila',
  'chwilę',
  'chyba',
  'ci',
  'ciało',
  'ciastko',
  'ciągle',
  'cicho',
  'cichy',
  'ciebie',
  'ciemno',
  'ciemny',
  'cienki',
  'ciepło',
  'ciepły',
  'cierpliwość',
  'cieszyć',
  'cię',
  'ciężki',
  'ciężko',
  'ciśnienie',
  'co',
  'cofnąć',
  'coraz',
  'coś',
  'córka',
  'cukier',
  'cukrzyca',
  'czapka',
  'czas',
  'czasem',
  'czekać',
  'czerwony',
  'często',
  'część',
  'człowiek',
  'czoło',
  'czterdzieści',
  'czternaście',
  'cztery',
  'czuć',
  'czujesz',
  'czuję',
  'czwartek',
  'czwarty',
  'czy',
  'czyj',
  'czym',
  'czysty',
  'czytać',
  'ćwiczenie',
  'dać',
  'daje',
  'dalej',
  'daleko',
  'dawka',
  'dawno',
  'dbać',
  'delikatnie',
  'delikatny',
  'dezynfekcja',
  'diagnoza',
  'dieta',
  'dla',
  'dlaczego',
  'dlatego',
  'dłoń',
  'długi',
  'długo',
  'dno',
  'do',
  'dobranoc',
  'dobry',
  'dobrze',
  'dodać',
  'dokąd',
  'dokładnie',
  'doktor',
  'dokuczliwy',
  'dom',
  'dopiero',
  'doskonale',
  'dostać',
  'dostawać',
  'dosyć',
  'dość',
  'dotknąć',
  'dowiedzieć',
  'dowód',
  'dożylnie',
  'droga',
  'drogi',
  'drugi',
  'drzwi',
  'dużo',
  'duży',
  'dwa',
  'dwadzieścia',
  'dwanaście',
  'dworzec',
  'dwudziesty',
  'dyżur',
  'dziadek',
  'działać',
  'dziecko',
  'dzielić',
  'dzielny',
  'dziennik',
  'dzień',
  'dziesiąty',
  'dziesięć',
  'dziewczyna',
  'dziewiąty',
  'dziewięć',
  'dzięki',
  'dziękować',
  'dziękuję',
  'dzisiaj',
  'dziś',
  'dziwnie',
  'dźwięk',
  'dźwigać',
  'energia',
  'fajny',
  'filiżanka',
  'fotel',
  'gabinet',
  'gardło',
  'gazik',
  'gdzie',
  'gdzieś',
  'gęsty',
  'gładki',
  'głodny',
  'głos',
  'głośno',
  'głośny',
  'głowa',
  'głód',
  'główny',
  'głupi',
  'gniew',
  'go',
  'godzina',
  'gorąco',
  'gorący',
  'gorączka',
  'gorszy',
  'gorzej',
  'gość',
  'gotować',
  'gotowy',
  'góra',
  'grać',
  'gruby',
  'grupa',
  'grypa',
  'guz',
  'guzik',
  'herbata',
  'ich',
  'idzie',
  'igła',
  'ile',
  'im',
  'imię',
  'inaczej',
  'informacja',
  'iniekcja',
  'inny',
  'iść',
  'ja',
  'jabłko',
  'jadę',
  'jajko',
  'jak',
  'jaki',
  'jakiś',
  'jako',
  'jasno',
  'jasny',
  'jechać',
  'jeden',
  'jedenaście',
  'jedzenie',
  'jedzie',
  'jedziesz',
  'jej',
  'jesień',
  'jest',
  'jestem',
  'jesteś',
  'jeszcze',
  'jeść',
  'jeśli',
  'jeżeli',
  'język',
  'jutro',
  'już',
  'kanapa',
  'kapcie',
  'karetka',
  'karta',
  'kaszel',
  'katar',
  'kawa',
  'kawałek',
  'kazać',
  'każdy',
  'kąpiel',
  'kciuk',
  'kiedy',
  'kiedyś',
  'kierunek',
  'kilka',
  'kino',
  'klatka',
  'klucz',
  'kłamać',
  'kłaść',
  'kłopot',
  'kobieta',
  'koc',
  'kochać',
  'kocham',
  'kolacja',
  'kolano',
  'kolega',
  'kolejny',
  'kolor',
  'kołdra',
  'kompot',
  'komu',
  'koniec',
  'koniecznie',
  'kończy',
  'kończyć',
  'korytarz',
  'kostka',
  'koszula',
  'koszulka',
  'kość',
  'kot',
  'krew',
  'kręci',
  'kręgosłup',
  'krok',
  'kroplówka',
  'krótki',
  'krwawienie',
  'krzesło',
  'krzyczeć',
  'książka',
  'kto',
  'ktoś',
  'który',
  'kubek',
  'kuchnia',
  'kupić',
  'kurtka',
  'kwadrans',
  'kwiat',
  'kwiecień',
  'lampa',
  'lato',
  'lecieć',
  'leczyć',
  'lekarski',
  'lekarstwo',
  'lekarz',
  'lekki',
  'lekko',
  'leniwy',
  'lepiej',
  'lepszy',
  'lewy',
  'leżanka',
  'leżeć',
  'leży',
  'linia',
  'lipiec',
  'list',
  'lista',
  'listopad',
  'liść',
  'litery',
  'lód',
  'lubi',
  'lubić',
  'lubię',
  'ludzie',
  'lustro',
  'luty',
  'lżejszy',
  'ładny',
  'łagodny',
  'łańcuch',
  'łatwy',
  'łazienka',
  'łokieć',
  'łopatka',
  'łóżko',
  'łydka',
  'łyżka',
  'łza',
  'ma',
  'maj',
  'maleńki',
  'mało',
  'mały',
  'mam',
  'mama',
  'martwić',
  'marzec',
  'masaż',
  'masło',
  'masz',
  'maść',
  'materiał',
  'mąż',
  'mdłości',
  'mi',
  'miasto',
  'miec',
  'mieć',
  'miejsce',
  'miesiąc',
  'między',
  'miękki',
  'mięsień',
  'miło',
  'miły',
  'mimo',
  'minuta',
  'mleko',
  'młody',
  'mnie',
  'mniej',
  'mnóstwo',
  'moc',
  'mocno',
  'mocny',
  'mogą',
  'mogę',
  'mogli',
  'mogła',
  'moja',
  'moje',
  'mokry',
  'moment',
  'monitor',
  'morze',
  'most',
  'mowa',
  'może',
  'możesz',
  'możliwy',
  'można',
  'mój',
  'mówić',
  'mówię',
  'mówisz',
  'mózg',
  'mu',
  'musieć',
  'musisz',
  'muszą',
  'muszę',
  'my',
  'myć',
  'myje',
  'mylić',
  'mysz',
  'myśl',
  'myśleć',
  'myślę',
  'na',
  'naczynia',
  'nad',
  'nadal',
  'nadgarstek',
  'nadzieja',
  'nagle',
  'nagły',
  'najlepiej',
  'najlepszy',
  'napić',
  'napisać',
  'napój',
  'naprawdę',
  'nareszcie',
  'nas',
  'nasilony',
  'nastrój',
  'nasz',
  'nasza',
  'nasze',
  'natychmiast',
  'nauczyć',
  'nawet',
  'nazywać',
  'nerka',
  'nerwowy',
  'nic',
  'nie',
  'niebo',
  'niedaleko',
  'niedługo',
  'niedobrze',
  'niedziela',
  'niego',
  'niej',
  'niektóry',
  'nieprzyjemny',
  'niespokojny',
  'niestety',
  'nieść',
  'nigdy',
  'nigdzie',
  'nikt',
  'niski',
  'nisko',
  'noc',
  'nocnik',
  'nocny',
  'noga',
  'normalnie',
  'normalny',
  'nos',
  'nosić',
  'notatka',
  'nowy',
  'nóż',
  'nudności',
  'nudny',
  'numer',
  'o',
  'obawiać',
  'obcy',
  'obecnie',
  'obiad',
  'obojczyk',
  'obok',
  'obowiązek',
  'ochota',
  'oczekiwać',
  'oczywiście',
  'od',
  'oddychać',
  'oddział',
  'odejść',
  'odpoczynek',
  'odpoczywać',
  'odpowiedzieć',
  'odpowiedź',
  'odwaga',
  'odwiedzić',
  'odwiedziny',
  'ogień',
  'ogólnie',
  'ogromny',
  'ogród',
  'ojciec',
  'okno',
  'oko',
  'okropny',
  'okulary',
  'on',
  'ona',
  'one',
  'oni',
  'ono',
  'opaska',
  'opatrunek',
  'opatrzyć',
  'operacja',
  'opiekować',
  'opisać',
  'opowiedzieć',
  'oprócz',
  'organizm',
  'ortopeda',
  'osiem',
  'osiemnaście',
  'osłabienie',
  'osoba',
  'ostatni',
  'ostro',
  'ostrożnie',
  'ostry',
  'otwarty',
  'otworzyć',
  'owoc',
  'owoce',
  'ósmy',
  'pacjent',
  'paczka',
  'pada',
  'palec',
  'pamiętać',
  'pan',
  'pani',
  'pantofel',
  'papier',
  'para',
  'parter',
  'patrzeć',
  'pełny',
  'pewien',
  'pewnie',
  'pewno',
  'pewny',
  'piasek',
  'piątek',
  'piąty',
  'picie',
  'pić',
  'pielęgniarka',
  'pielęgniarz',
  'pieniądze',
  'pierś',
  'pierwszy',
  'pies',
  'pięć',
  'piękny',
  'pięta',
  'piętnaście',
  'piętro',
  'piją',
  'piję',
  'pilny',
  'pisać',
  'piszę',
  'piżama',
  'plaster',
  'plecy',
  'płacić',
  'płakać',
  'płuca',
  'płyn',
  'po',
  'pobyt',
  'początek',
  'poczekalnia',
  'pod',
  'podać',
  'podawać',
  'podczas',
  'podekscytowany',
  'podjazd',
  'podłoga',
  'podnieść',
  'podoba',
  'podobać',
  'podobnie',
  'poduszka',
  'podwórko',
  'pogoda',
  'pogotowie',
  'pokazać',
  'pokój',
  'pole',
  'policzek',
  'południe',
  'pomagać',
  'pomagam',
  'pomarańcza',
  'pomidor',
  'pomieszczenie',
  'pomoc',
  'pomóc',
  'pomyśleć',
  'ponad',
  'poniedziałek',
  'ponieważ',
  'poprosić',
  'poranek',
  'porozmawiać',
  'portfel',
  'posiłek',
  'pościel',
  'potem',
  'potrafi',
  'potrafię',
  'potrzeba',
  'potrzebny',
  'potrzebować',
  'potrzebuję',
  'poważnie',
  'poważny',
  'powiedzieć',
  'powietrze',
  'powinien',
  'powinienem',
  'powinnam',
  'powoli',
  'powtórzyć',
  'poznać',
  'pozwolić',
  'pożyczyć',
  'pójść',
  'północ',
  'późnej',
  'później',
  'późno',
  'praca',
  'pracować',
  'pracownik',
  'pracuję',
  'pralka',
  'prawdopodobnie',
  'prawdziwy',
  'prawie',
  'prawo',
  'prawy',
  'problem',
  'promieniujący',
  'prosić',
  'prosto',
  'prosty',
  'proszek',
  'proszę',
  'prowadzić',
  'próbować',
  'prysznic',
  'prywatny',
  'przed',
  'przede',
  'przedtem',
  'przedwczoraj',
  'przejść',
  'przepraszam',
  'przerażony',
  'przestać',
  'przestraszony',
  'przez',
  'przeziębienie',
  'przy',
  'przychodzić',
  'przygotować',
  'przyjaciel',
  'przyjaciółka',
  'przyjąć',
  'przyjdzie',
  'przyjemny',
  'przyjść',
  'przykro',
  'przynajmniej',
  'przynieść',
  'przypadek',
  'przyszedł',
  'pulsujący',
  'punkt',
  'pusty',
  'pytać',
  'pytanie',
  'raczej',
  'radosny',
  'ramię',
  'rana',
  'rano',
  'raz',
  'razem',
  'recepta',
  'regularnie',
  'rehabilitacja',
  'rentgen',
  'ręce',
  'ręcznik',
  'ręka',
  'rękawiczki',
  'robi',
  'robić',
  'robię',
  'robisz',
  'rodzice',
  'rodzina',
  'rok',
  'rower',
  'rozczarowany',
  'rozmowa',
  'rozumieć',
  'rozumiem',
  'równie',
  'również',
  'równy',
  'ruch',
  'ruszać',
  'ruszyć',
  'rwący',
  'ryba',
  'ryzyko',
  'rzadko',
  'rzecz',
  'rzeczywiście',
  'rzepka',
  'sala',
  'salon',
  'sam',
  'sama',
  'samochód',
  'samodzielny',
  'samolot',
  'samotny',
  'sąsiad',
  'schodki',
  'schody',
  'sen',
  'serce',
  'siebie',
  'siedem',
  'siedemnaście',
  'siedzi',
  'siedzieć',
  'sierpień',
  'się',
  'silny',
  'siła',
  'siostra',
  'siódmy',
  'skarpetki',
  'skąd',
  'sklep',
  'sklepik',
  'skoro',
  'skóra',
  'skurcz',
  'słaby',
  'słodki',
  'słońce',
  'słowo',
  'słuchać',
  'słyszeć',
  'smaczny',
  'smak',
  'smutny',
  'sobota',
  'sok',
  'spać',
  'specjalista',
  'spodnie',
  'spojrzeć',
  'spokojnie',
  'spokojny',
  'spokój',
  'sporo',
  'sport',
  'sposób',
  'spóźniony',
  'spragniony',
  'sprawdzić',
  'spytać',
  'stać',
  'stały',
  'stamtąd',
  'stan',
  'stary',
  'staw',
  'stąd',
  'sto',
  'stoi',
  'stolik',
  'stopa',
  'stół',
  'strach',
  'strasznie',
  'straszny',
  'strona',
  'strzykawka',
  'suchy',
  'sukienka',
  'swoja',
  'swoje',
  'swój',
  'syn',
  'sypialnia',
  'szafka',
  'szanować',
  'szczególnie',
  'szczepienie',
  'szczerze',
  'szczęka',
  'szczęśliwy',
  'szept',
  'szeptem',
  'szeroki',
  'szesnście',
  'sześć',
  'szklanka',
  'szkło',
  'szkoda',
  'szkoła',
  'szlafrok',
  'szósty',
  'szpital',
  'szuflada',
  'szybki',
  'szybko',
  'szyja',
  'śliczny',
  'ślub',
  'śmiać',
  'śniadanie',
  'śnieg',
  'śpiący',
  'śpieszyć',
  'śpię',
  'średni',
  'środa',
  'środek',
  'świat',
  'światło',
  'świąteczny',
  'świeży',
  'święto',
  'ta',
  'tabletka',
  'tablica',
  'tak',
  'taki',
  'także',
  'talerz',
  'tam',
  'tamta',
  'tamten',
  'tamto',
  'tani',
  'tata',
  'te',
  'telefon',
  'telewizor',
  'temperatura',
  'ten',
  'terapia',
  'teraz',
  'termometr',
  'test',
  'też',
  'tępy',
  'tętno',
  'tlen',
  'to',
  'toaleta',
  'torba',
  'tramwaj',
  'trochę',
  'trudno',
  'trudny',
  'trwać',
  'trzeba',
  'trzeci',
  'trzy',
  'trzydziesty',
  'trzydzieści',
  'trzymać',
  'trzymam',
  'trzynaście',
  'tu',
  'tutaj',
  'twardy',
  'twarz',
  'twoja',
  'twoje',
  'twój',
  'ty',
  'tydzień',
  'tylko',
  'tył',
  'tysiąc',
  'u',
  'ubierać',
  'ubranie',
  'ucho',
  'uczyć',
  'udać',
  'udar',
  'udo',
  'ufać',
  'ulica',
  'ulubiony',
  'umieć',
  'umówić',
  'umyć',
  'uraz',
  'usta',
  'uwaga',
  'uważać',
  'używać',
  'w',
  'waga',
  'wanna',
  'warga',
  'was',
  'ważny',
  'wąski',
  'wątroba',
  'wcale',
  'wcześnie',
  'wcześniej',
  'wczoraj',
  'wdzięczny',
  'weekend',
  'wejście',
  'wejść',
  'wesoły',
  'widać',
  'widelec',
  'widzę',
  'widzieć',
  'widzisz',
  'wie',
  'wieczorem',
  'wieczór',
  'wiedzieć',
  'wiele',
  'wielki',
  'wiem',
  'wiemy',
  'wierzyć',
  'wiesz',
  'wieś',
  'więc',
  'więcej',
  'większość',
  'większy',
  'winda',
  'wiosna',
  'witamina',
  'wizyta',
  'wkrótce',
  'właściwie',
  'właśnie',
  'woda',
  'woleć',
  'wolno',
  'wolny',
  'wózek',
  'wracać',
  'wracam',
  'wreszcie',
  'wrócić',
  'wrzesień',
  'wspaniały',
  'wspomnieć',
  'wspólny',
  'wstaje',
  'wstawać',
  'wstawaj',
  'wstrząs',
  'wszystkie',
  'wszystko',
  'wtedy',
  'wtorek',
  'wy',
  'wybrać',
  'wychodzić',
  'wydawać',
  'wyglądać',
  'wygodny',
  'wyjaśnić',
  'wyjście',
  'wyjść',
  'wymiotować',
  'wynik',
  'wyniki',
  'wypić',
  'wypisać',
  'wyraźnie',
  'wyraźny',
  'wysoki',
  'wysoko',
  'wystarczy',
  'wyżej',
  'wziąć',
  'wzrok',
  'z',
  'za',
  'zabieg',
  'zabrać',
  'zachować',
  'zachwycony',
  'zacząć',
  'zaczynać',
  'zadowolony',
  'zadzwonić',
  'zagłówek',
  'zajęty',
  'zakażenie',
  'zaledwie',
  'zamknąć',
  'zamknięty',
  'zamówić',
  'zamykać',
  'zapalenie',
  'zapomnieć',
  'zapytać',
  'zaraz',
  'zasłabnąć',
  'zasnąć',
  'zastrzyk',
  'zaufanie',
  'zawał',
  'zawołać',
  'zawroty',
  'zawsze',
  'zazwyczaj',
  'ząb',
  'zdenerwowany',
  'zdjęcie',
  'zdrowia',
  'zdrowie',
  'zdrowy',
  'zdumiony',
  'ze',
  'zegar',
  'zegarek',
  'zerknąć',
  'zeszły',
  'zewnątrz',
  'zielony',
  'ziemia',
  'zima',
  'zimno',
  'zimny',
  'zirytowany',
  'złamanie',
  'zły',
  'zmęczenie',
  'zmęczony',
  'zmiana',
  'zmienić',
  'zmierzyć',
  'znaczyć',
  'znać',
  'znajdować',
  'znaleźć',
  'znam',
  'znany',
  'znasz',
  'znowu',
  'znudzony',
  'zobaczyć',
  'zostać',
  'zostawić',
  'zrelaksowany',
  'zrobić',
  'zrozumieć',
  'zupa',
  'zupełnie',
  'zupełny',
  'zwichnięcie',
  'zwykle',
  'zwykły',
  'źle',
  'źródło',
  'żaden',
  'żałować',
  'że',
  'żebro',
  'żeby',
  'żołądek',
  'żona',
  'żółty',
  'żuchwa',
  'życie',
  'życzyć',
  'żyć',
  'żywy'
];

// --- Bigrams (word -> likely next words, 150+ entries) ---
const BIGRAMS = {
  'a': ['ty', 'to', 'może', 'jak', 'co', 'gdzie', 'kiedy'],
  'ale': ['nie', 'to', 'ja', 'tak', 'bardzo', 'chcę', 'jestem'],
  'albo': ['nie', 'tak', 'to', 'może', 'coś'],
  'apteka': ['jest', 'blisko', 'gdzie'],
  'babcia': ['jest', 'przyjdzie', 'dzwoniła'],
  'badanie': ['krwi', 'jest', 'kiedy', 'było', 'będzie'],
  'bardzo': ['boli', 'dobrze', 'źle', 'proszę', 'chcę', 'dziękuję', 'mi', 'dużo'],
  'bez': ['problemu', 'tego', 'sensu', 'bólu'],
  'bo': ['mnie', 'boli', 'nie', 'chcę', 'jestem', 'to'],
  'boli': ['mnie', 'głowa', 'brzuch', 'ręka', 'noga', 'bardzo', 'serce', 'plecy', 'tutaj', 'tu'],
  'brat': ['jest', 'przyjdzie', 'dzwonił', 'mój'],
  'będę': ['czekać', 'spać', 'jeść', 'pić', 'leżeć'],
  'będzie': ['dobrze', 'lepiej', 'można', 'kiedy', 'jutro'],
  'był': ['tutaj', 'lekarz', 'wczoraj', 'tu'],
  'była': ['tutaj', 'pielęgniarka', 'wczoraj'],
  'całkiem': ['dobrze', 'nieźle', 'spokojnie'],
  'chcę': ['pić', 'jeść', 'spać', 'iść', 'wiedzieć', 'to', 'mieć', 'do', 'zobaczyć', 'wstać'],
  'chcesz': ['pić', 'jeść', 'spać', 'coś', 'to'],
  'chce': ['pić', 'jeść', 'spać', 'iść'],
  'chyba': ['tak', 'nie', 'jest', 'będzie', 'mogę'],
  'ci': ['dziękuję', 'pomogę', 'powiem', 'dam'],
  'ciepło': ['mi', 'jest', 'tutaj'],
  'ciężko': ['mi', 'jest', 'oddychać', 'mówić'],
  'co': ['to', 'jest', 'się', 'robisz', 'słychać', 'mam', 'będzie', 'chcesz', 'mogę', 'nowego'],
  'coś': ['mnie', 'boli', 'jest', 'się', 'chcę'],
  'córka': ['jest', 'przyjdzie', 'moja', 'dzwoniła'],
  'czas': ['na', 'jest', 'już'],
  'czasem': ['boli', 'jest', 'tak', 'nie'],
  'czekać': ['na', 'muszę', 'długo', 'ile'],
  'czy': ['możesz', 'można', 'jest', 'masz', 'będziesz', 'to', 'mogę', 'pan', 'pani'],
  'czuję': ['się', 'ból', 'to'],
  'daleko': ['jest', 'stąd', 'do'],
  'dać': ['mi', 'to', 'wodę', 'jeść', 'pić'],
  'dla': ['mnie', 'ciebie', 'niego', 'niej', 'nas', 'dzieci'],
  'dlaczego': ['nie', 'tak', 'to', 'jest', 'muszę'],
  'dlatego': ['że', 'nie', 'chcę', 'jestem'],
  'długo': ['jeszcze', 'to', 'będę', 'trzeba', 'czekać'],
  'do': ['domu', 'łazienki', 'szpitala', 'lekarza', 'tego', 'widzenia', 'pracy'],
  'dobranoc': ['kochanie', 'wszystkim'],
  'dobrze': ['się', 'że', 'jest', 'dziękuję', 'to'],
  'dokąd': ['idziesz', 'jedziesz', 'to'],
  'dom': ['jest', 'mój', 'daleko', 'blisko'],
  'dostać': ['mogę', 'wodę', 'tabletki', 'jeść', 'herbatę'],
  'dużo': ['wody', 'czasu', 'lepiej', 'gorzej'],
  'dziadek': ['jest', 'przyjdzie', 'dzwonił'],
  'dziecko': ['jest', 'moje', 'płacze', 'śpi'],
  'dzień': ['dobry', 'jest', 'dzisiaj'],
  'dziś': ['jest', 'rano', 'wieczorem', 'lepiej', 'gorzej'],
  'dzisiaj': ['jest', 'rano', 'wieczorem', 'lepiej', 'gorzej'],
  'dziękuję': ['bardzo', 'za', 'ci', 'pani', 'panu'],
  'gardło': ['boli', 'mnie', 'suche'],
  'gorąco': ['mi', 'jest', 'tutaj'],
  'gorączka': ['jest', 'mam', 'wysoka', 'duża'],
  'gorzej': ['mi', 'jest', 'się', 'niż'],
  'gdzie': ['jest', 'są', 'mogę', 'mam', 'to', 'idę', 'łazienka', 'lekarz'],
  'głodny': ['jestem', 'bardzo', 'trochę'],
  'głowa': ['boli', 'mnie', 'kręci'],
  'idę': ['do', 'na', 'tam', 'spać'],
  'ile': ['to', 'kosztuje', 'czasu', 'razy', 'dni', 'jeszcze'],
  'ja': ['chcę', 'jestem', 'mam', 'mogę', 'nie', 'wiem', 'rozumiem', 'też'],
  'jak': ['tam', 'się', 'długo', 'jest', 'to', 'masz', 'ci', 'mogę', 'będzie'],
  'jaki': ['jest', 'to', 'dzień', 'ból'],
  'jest': ['dobrze', 'źle', 'zimno', 'gorąco', 'ciepło', 'późno', 'wcześnie', 'tu', 'to', 'lekarz'],
  'jestem': ['głodny', 'spragniony', 'zmęczony', 'chory', 'smutny', 'szczęśliwy', 'gotowy', 'spokojny', 'tu', 'sam'],
  'jeszcze': ['nie', 'raz', 'trochę', 'jeden', 'jedno', 'coś'],
  'jeść': ['chcę', 'mogę', 'coś', 'nie'],
  'jeśli': ['mogę', 'chcesz', 'tak', 'nie', 'można'],
  'jutro': ['jest', 'będzie', 'rano', 'przyjdzie'],
  'już': ['nie', 'jest', 'dobrze', 'czas', 'idę', 'wiem', 'lepiej'],
  'każdy': ['dzień', 'raz', 'wie'],
  'kaszel': ['mam', 'jest', 'suchy', 'mokry'],
  'kiedy': ['przyjdzie', 'będzie', 'mogę', 'jest', 'to', 'lekarz', 'obiad', 'można'],
  'kilka': ['minut', 'godzin', 'dni', 'razy'],
  'koc': ['proszę', 'jest', 'ciepły', 'za'],
  'kocham': ['cię', 'was', 'mamę', 'tatę'],
  'kto': ['to', 'jest', 'przyszedł', 'dzwonił', 'tu', 'tam'],
  'ktoś': ['jest', 'przyszedł', 'dzwoni', 'tu'],
  'lekarz': ['przyjdzie', 'jest', 'kiedy', 'powiedział', 'mówi', 'gdzie'],
  'lekarstwo': ['na', 'ból', 'gorączkę'],
  'lepiej': ['mi', 'się', 'jest', 'już', 'czuję'],
  'lubię': ['to', 'jeść', 'pić', 'herbatę', 'kawę'],
  'łóżko': ['proszę', 'podnieść', 'położyć', 'jest'],
  'ma': ['być', 'to', 'przyjść', 'pan', 'pani'],
  'mama': ['jest', 'przyjdzie', 'dzwoniła', 'moja', 'gdzie'],
  'mam': ['pytanie', 'prośbę', 'ból', 'gorączkę', 'problem', 'dość', 'ochotę'],
  'masz': ['rację', 'czas', 'to', 'coś'],
  'mało': ['wody', 'jedzenia', 'czasu', 'sił'],
  'mąż': ['jest', 'przyjdzie', 'mój', 'dzwonił'],
  'mi': ['zimno', 'gorąco', 'ciepło', 'lepiej', 'gorzej', 'smutno', 'dobrze', 'źle', 'się'],
  'mimo': ['to', 'że', 'wszystko', 'bólu'],
  'mnie': ['boli', 'jest', 'zimno', 'gorąco', 'nie'],
  'mniej': ['boli', 'niż', 'więcej'],
  'mogę': ['prosić', 'dostać', 'powiedzieć', 'iść', 'zjeść', 'wypić', 'spać'],
  'mogą': ['przyjść', 'pomóc', 'to'],
  'może': ['być', 'tak', 'nie', 'jutro', 'później', 'pan', 'pani'],
  'możesz': ['mi', 'pomóc', 'podać', 'przyjść', 'powiedzieć', 'to'],
  'można': ['prosić', 'otworzyć', 'zamknąć', 'iść'],
  'muszę': ['iść', 'pić', 'jeść', 'spać', 'do', 'wstać'],
  'musisz': ['jeść', 'pić', 'odpocząć', 'spać'],
  'mówić': ['mogę', 'chcę', 'nie', 'wolniej'],
  'mówię': ['ci', 'że', 'poważnie', 'prawdę'],
  'na': ['pewno', 'razie', 'to', 'górze', 'dole', 'obiad', 'śniadanie', 'kolację'],
  'nad': ['ranem', 'łóżkiem', 'głową'],
  'naprawdę': ['tak', 'nie', 'chcę', 'jest', 'dziękuję'],
  'nas': ['jest', 'nie', 'tu'],
  'nawet': ['nie', 'tak', 'jeśli', 'jak'],
  'nie': ['wiem', 'mogę', 'chcę', 'mam', 'jestem', 'rozumiem', 'lubię', 'boli', 'trzeba', 'ma'],
  'nic': ['nie', 'mi', 'się', 'to', 'strasznego'],
  'niech': ['pan', 'pani', 'będzie', 'to'],
  'nigdy': ['nie', 'więcej', 'tego'],
  'nikt': ['nie', 'tu'],
  'noc': ['była', 'jest', 'dobra'],
  'noga': ['boli', 'mnie', 'lewa', 'prawa'],
  'o': ['co', 'tym', 'czym', 'której', 'ile'],
  'obiad': ['jest', 'kiedy', 'będzie', 'chcę'],
  'od': ['rana', 'wczoraj', 'kiedy', 'tego', 'dawna'],
  'oddychać': ['ciężko', 'trudno', 'nie', 'mogę'],
  'oko': ['boli', 'mnie', 'lewe', 'prawe'],
  'okno': ['proszę', 'otworzyć', 'zamknąć', 'jest'],
  'on': ['jest', 'ma', 'chce', 'mówi', 'może'],
  'ona': ['jest', 'ma', 'chce', 'mówi', 'może'],
  'operacja': ['kiedy', 'jest', 'będzie', 'była'],
  'osoba': ['ta', 'jest', 'która'],
  'pewnie': ['tak', 'nie', 'jest', 'będzie'],
  'pielęgniarka': ['jest', 'przyjdzie', 'gdzie', 'proszę', 'zawołaj'],
  'pić': ['chcę', 'mogę', 'wodę', 'herbatę', 'kawę'],
  'plecy': ['bolą', 'mnie', 'tutaj'],
  'po': ['co', 'to', 'obiedzie', 'śniadaniu', 'kolacji', 'południu'],
  'pod': ['łóżkiem', 'poduszką', 'głową'],
  'podać': ['mi', 'wodę', 'to', 'proszę'],
  'poduszka': ['jest', 'proszę', 'za', 'wysoka', 'niska'],
  'potem': ['będę', 'mogę', 'może', 'przyjdzie'],
  'potrzebuję': ['pomocy', 'wody', 'leku', 'odpoczynku', 'jedzenia'],
  'powoli': ['proszę', 'mówić', 'iść'],
  'praca': ['jest', 'moja', 'w'],
  'prawie': ['dobrze', 'tak', 'nie', 'gotowe'],
  'problem': ['jest', 'mam', 'z', 'duży'],
  'prosić': ['o', 'mogę', 'chcę'],
  'proszę': ['o', 'podać', 'pomóc', 'powiedzieć', 'przyjść', 'zadzwonić', 'bardzo', 'poczekać', 'otworzyć', 'zamknąć'],
  'przed': ['obiadem', 'snem', 'operacją', 'wizytą'],
  'przepraszam': ['za', 'nie', 'czy', 'że'],
  'przy': ['łóżku', 'oknie', 'drzwiach'],
  'przyjdzie': ['lekarz', 'kiedy', 'jutro', 'dzisiaj'],
  'przyjść': ['może', 'kiedy', 'mogę', 'jutro'],
  'pytanie': ['mam', 'jest', 'jedno'],
  'rano': ['jest', 'było', 'dzisiaj', 'jutro', 'wczoraj'],
  'raz': ['jeszcze', 'dziennie', 'na', 'w'],
  'razem': ['z', 'będziemy', 'możemy'],
  'recepta': ['jest', 'na', 'gdzie'],
  'rentgen': ['kiedy', 'jest', 'będzie', 'był'],
  'robić': ['co', 'nie', 'mogę', 'muszę'],
  'robię': ['to', 'co', 'wszystko'],
  'rodzina': ['jest', 'moja', 'przyjdzie', 'gdzie'],
  'rozumiem': ['to', 'nie', 'dobrze', 'że'],
  'ręka': ['boli', 'mnie', 'lewa', 'prawa'],
  'sam': ['jestem', 'nie', 'mogę', 'wiem'],
  'serce': ['boli', 'mnie', 'moje'],
  'się': ['czuję', 'boję', 'cieszę', 'martwię', 'staram', 'dobrze', 'źle'],
  'siostra': ['jest', 'przyjdzie', 'moja', 'dzwoniła'],
  'skąd': ['jesteś', 'to', 'wiesz', 'masz'],
  'spać': ['chcę', 'mogę', 'nie', 'idę'],
  'spokojnie': ['proszę', 'jest', 'będzie'],
  'syn': ['jest', 'przyjdzie', 'mój', 'dzwonił'],
  'szpital': ['jest', 'gdzie', 'w', 'jaki'],
  'szybko': ['proszę', 'jest', 'bardzo'],
  'tak': ['jest', 'samo', 'bardzo', 'dobrze', 'chcę', 'myślę', 'proszę'],
  'tabletka': ['na', 'ból', 'kiedy', 'proszę'],
  'tam': ['jest', 'idę', 'było', 'są'],
  'tata': ['jest', 'przyjdzie', 'mój', 'dzwonił', 'gdzie'],
  'teraz': ['jest', 'mogę', 'chcę', 'nie', 'dobrze', 'już', 'proszę'],
  'termometr': ['proszę', 'jest', 'gdzie'],
  'to': ['jest', 'dobrze', 'źle', 'prawda', 'wszystko', 'było', 'nie', 'co', 'ja', 'moje'],
  'trochę': ['lepiej', 'gorzej', 'boli', 'wody', 'więcej'],
  'trzeba': ['poczekać', 'iść', 'zrobić', 'wziąć'],
  'tu': ['jest', 'jestem', 'boli', 'nie'],
  'tutaj': ['jest', 'boli', 'proszę', 'nie'],
  'tylko': ['trochę', 'chwilę', 'raz', 'to'],
  'ucho': ['boli', 'mnie', 'lewe', 'prawe'],
  'w': ['porządku', 'domu', 'szpitalu', 'nocy', 'dzień', 'pokoju'],
  'was': ['kocham', 'proszę', 'dziękuję'],
  'wiem': ['że', 'to', 'jak', 'co', 'gdzie'],
  'woda': ['proszę', 'jest', 'zimna', 'ciepła', 'gdzie'],
  'wolno': ['mi', 'mówić', 'proszę', 'jest'],
  'wszystko': ['dobrze', 'jest', 'w', 'będzie', 'rozumiem'],
  'wtorek': ['jest', 'był', 'będzie'],
  'wczoraj': ['było', 'był', 'była', 'rano', 'wieczorem'],
  'więcej': ['wody', 'jedzenia', 'nie', 'proszę'],
  'wizyta': ['kiedy', 'jest', 'była', 'będzie'],
  'za': ['chwilę', 'dużo', 'mało', 'późno', 'wcześnie', 'to', 'zimno', 'gorąco'],
  'zaraz': ['przyjdę', 'będzie', 'wracam', 'wrócę'],
  'zastrzyk': ['kiedy', 'jest', 'będzie', 'boli'],
  'zawsze': ['tak', 'jest', 'mogę', 'boli'],
  'ze': ['mną', 'sobą', 'szpitala'],
  'zimno': ['mi', 'jest', 'tutaj', 'bardzo'],
  'zmęczony': ['jestem', 'bardzo', 'trochę'],
  'znowu': ['boli', 'jest', 'nie', 'to'],
  'źle': ['się', 'mi', 'jest', 'czuję'],
  'żona': ['jest', 'przyjdzie', 'moja', 'dzwoniła']
};
